// Theme Design Tokens - Matched to UI designs exactly

export const lightTheme = {
  colors: {
    background: {
      primary: '#F8F9FA',
      secondary: '#F1F3F5',
    },
    surface: {
      default: '#FFFFFF',
      elevated: '#FFFFFF',
    },
    text: {
      primary: '#1A1A1A',
      secondary: '#6B7280',
      tertiary: '#9CA3AF',
      disabled: '#D1D5DB',
      inverse: '#FFFFFF',
    },
    border: {
      default: '#E5E7EB',
      light: '#F3F4F6',
    },
    action: {
      primary: '#2D6A4F',
      primaryPressed: '#1B4332',
      primarySoft: '#D1FAE5',
      secondary: '#40916C',
      destructive: '#DC2626',
      destructiveSoft: '#FEE2E2',
    },
    status: {
      success: '#2D6A4F',
      successSoft: '#D1FAE5',
      warning: '#F59E0B',
      warningSoft: '#FEF3C7',
      error: '#DC2626',
      errorSoft: '#FEE2E2',
      info: '#3B82F6',
      infoSoft: '#DBEAFE',
    },
    record: {
      lab: '#3B82F6',
      labSoft: '#DBEAFE',
      prescription: '#2D6A4F',
      prescriptionSoft: '#D1FAE5',
      consultation: '#7C3AED',
      consultationSoft: '#EDE9FE',
      vaccination: '#06B6D4',
      vaccinationSoft: '#CFFAFE',
      allergy: '#F97316',
      allergySoft: '#FFEDD5',
    },
    rating: '#F59E0B',
    skeleton: '#E5E7EB',
    skeletonHighlight: '#F3F4F6',
    overlay: 'rgba(0, 0, 0, 0.5)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    xxxxl: 40,
    xxxxxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    pill: 999,
  },
  typography: {
    display: { fontSize: 32, lineHeight: 40, fontWeight: '700' as const },
    h1: { fontSize: 24, lineHeight: 32, fontWeight: '700' as const },
    h2: { fontSize: 20, lineHeight: 28, fontWeight: '700' as const },
    h3: { fontSize: 18, lineHeight: 24, fontWeight: '600' as const },
    h4: { fontSize: 16, lineHeight: 22, fontWeight: '600' as const },
    bodyLarge: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
    body: { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
    bodySmall: { fontSize: 12, lineHeight: 16, fontWeight: '400' as const },
    caption: { fontSize: 11, lineHeight: 14, fontWeight: '400' as const },
    button: { fontSize: 16, lineHeight: 20, fontWeight: '600' as const },
    label: { fontSize: 12, lineHeight: 16, fontWeight: '600' as const },
    price: { fontSize: 18, lineHeight: 24, fontWeight: '700' as const },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
};

export const darkTheme: typeof lightTheme = {
  ...lightTheme,
  colors: {
    ...lightTheme.colors,
    background: {
      primary: '#0F1512',
      secondary: '#1F2A23',
    },
    surface: {
      default: '#17201B',
      elevated: '#1F2A23',
    },
    text: {
      primary: '#EDF3EE',
      secondary: '#A8B5AC',
      tertiary: '#6B7B71',
      disabled: '#4A5A50',
      inverse: '#1A1A1A',
    },
    border: {
      default: '#2A362F',
      light: '#1F2A23',
    },
    action: {
      primary: '#5FBF8A',
      primaryPressed: '#4CC48A',
      primarySoft: '#1E3A2C',
      secondary: '#6BCB95',
      destructive: '#F87171',
      destructiveSoft: '#3B1515',
    },
    status: {
      success: '#4CC48A',
      successSoft: '#1E3A2C',
      warning: '#FBBF24',
      warningSoft: '#3B2F0A',
      error: '#F87171',
      errorSoft: '#3B1515',
      info: '#60A5FA',
      infoSoft: '#15233B',
    },
    skeleton: '#2A362F',
    skeletonHighlight: '#3A4A3F',
    overlay: 'rgba(0, 0, 0, 0.7)',
  },
};

export type Theme = typeof lightTheme;
